apiVersion: v1
kind: Pod
metadata:
  name: bertinference
spec:
  containers:
    - name: python
      image: jehillparikh/bertinference:v10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: bertinference
  name: bertinference
spec:
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: bertinference
  type: LoadBalancer            