apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisdisk
spec:
  storageClassName: ""
  capacity:
    storage: 30G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: redis-disk-gce
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdata
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: redisdisk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
